# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 641b3b9879f1d9c1efa2a9962863ae57c4619900c79454e66dc6340bf700fd84bd37db24c844338bf0fd3427f7ea275f1dc48657f9de9e66a85485e9c288e47d

test:
  secret_key_base: f3fa4d591a74a3404eef24e6946c7caddb7c55900debf2e0fc95e417675b3d7a2aa49bc1b5d017a1ca9545acc94c6d837a02583bb45b849ee40c0f9e219affa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
